/**
 * Barrel export for all configuration
 */

export {
  DEFAULT_TRANSLATION_CONFIG,
  BROWSER_CONFIG,
  KAGI_TRANSLATE_BASE_URL,
  KAGI_SELECTORS,
  TRANSLATION_STYLE_UI_LABELS,
  FORMALITY_UI_LABELS,
  SPEAKER_GENDER_UI_LABELS,
  ADDRESSEE_GENDER_UI_LABELS,
  GENDER_PREFERENCE_UI_LABELS,
  MAX_TRANSLATION_CONTEXT_LENGTH,
  clampTranslationContext,
  INDEX_ENTRY_SAMPLE_TRANSLATION_CONTEXT,
  getReadingLevelSliderValue,
  getDefaultTranslationOptions,
} from './translation.config'
