import { readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { $ } from 'bun'

/**
 * Generate daily performance report by analyzing traces and creating markdown summary.
 *
 * Usage:
 *   bun run scripts/generate-daily-report.ts [YYYY-MM-DD]
 *
 * If no date provided, uses today's date.
 */
async function generateDailyReport(date: string): Promise<void> {
  const traceDir = join('./output/traces', date)

  try {
    // Check if directory exists and has traces
    const files = await readdir(traceDir)
    const traceCount = files.filter((f) => f.startsWith('trace-') && f.endsWith('.json')).length

    if (traceCount === 0) {
      console.error(`No trace files found in ${traceDir}`)
      process.exit(1)
    }

    console.log(`Found ${traceCount} trace(s) for ${date}`)
  } catch (error) {
    console.error(`Failed to access traces for ${date}:`, error)
    console.error(`Make sure ${traceDir} exists and contains trace files.`)
    process.exit(1)
  }

  // Run analysis script and capture JSON output
  const analysisFile = join('./output/analysis', `analysis-${date}.json`)

  try {
    console.log(`Analyzing traces...`)
    await $`bun run scripts/analyze-traces.ts ${traceDir} ${analysisFile}`.quiet()

    // Read analysis results
    const analysisData = await Bun.file(analysisFile).json()

    // Generate markdown report
    const report = buildMarkdownReport(date, analysisData)

    // Write report
    const reportPath = join('./docs/analysis', `daily-report-${date}.md`)
    await Bun.write(reportPath, report)

    console.log(`\n✓ Report generated: ${reportPath}`)
    console.log(`✓ Analysis data saved: ${analysisFile}`)
  } catch (error) {
    console.error('Failed to generate report:', error)
    process.exit(1)
  }
}

function buildMarkdownReport(date: string, analysis: {
  summary: {
    totalRequests: number
    avgLatencyMs: number
    p50: number
    p95: number
    p99: number
  }
  byProvider: Record<string, {
    count: number
    avgLLMTime: number
    avgTotal: number
    tokensPerRequest: number
  }>
  bottlenecks: {
    stage: string
    occurrences: number
    avgDuration: number
  }[]
  opportunities: {
    cacheCandidate: number
    fastModelCandidate: number
    keywordOptimization: number
  }
  slowRequests: Array<{
    traceId: string
    duration: number
    bottleneck: string
    provider: string
  }>
}): string {
  const providerSection = Object.entries(analysis.byProvider)
    .map(
      ([provider, stats]) => `
### ${provider}

- Count: ${stats.count}
- Avg LLM time: ${stats.avgLLMTime}ms
- Avg total: ${stats.avgTotal}ms
- Tokens/request: ${stats.tokensPerRequest}
`,
    )
    .join('')

  const bottlenecksSection = analysis.bottlenecks
    .map((b) => `- **${b.stage}:** ${b.occurrences} occurrences (avg ${b.avgDuration}ms)`)
    .join('\n')

  const slowRequestsSection =
    analysis.slowRequests.length > 0
      ? `
## Slowest Requests

${analysis.slowRequests
  .slice(0, 5)
  .map((req) => `- \`${req.traceId}\`: ${req.duration}ms (${req.bottleneck} bottleneck, ${req.provider})`)
  .join('\n')}
`
      : ''

  return `# Daily Performance Report - ${date}

## Summary

- **Total Requests:** ${analysis.summary.totalRequests}
- **Avg Latency:** ${analysis.summary.avgLatencyMs}ms
- **P50 Latency:** ${analysis.summary.p50}ms
- **P95 Latency:** ${analysis.summary.p95}ms
- **P99 Latency:** ${analysis.summary.p99}ms

## Provider Performance
${providerSection}
## Bottlenecks
${bottlenecksSection}

## Optimization Opportunities

- Cache candidates: ${analysis.opportunities.cacheCandidate}
- Fast model candidates: ${analysis.opportunities.fastModelCandidate}
- Keyword optimization needed: ${analysis.opportunities.keywordOptimization}
${slowRequestsSection}
---

*Generated by generate-daily-report.ts at ${new Date().toISOString()}*
`.trim()
}

// CLI usage
const date = process.argv[2] || new Date().toISOString().split('T')[0]
await generateDailyReport(date)
